---
# deploy_wordpress.yml
- hosts: localhost
  connection: local
  tasks:
    - name: Add bitnami helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
      environment:
        KUBECONFIG: /workspace/k3s.yaml

    - name: Create WordPress values file
      copy:
        dest: /workspace/wordpress-values.yaml
        content: |
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
          ingress:
            enabled: false
          mariadb:
            auth:
              rootPassword: "Change_this_root_password_123"
              database: wordpress
              username: wordpress
              password: "Change_this_db_password_123"
          wordpressPassword: "Change_this_wp_password_123"
          wordpressEmail: "admin@example.com"
          wordpressUsername: admin
          persistence:
            enabled: true
            size: 10Gi
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          mariadb:
            primary:
              persistence:
                enabled: true
                size: 8Gi
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 250m
                  memory: 256Mi

    - name: Deploy WordPress
      kubernetes.core.helm:
        name: wordpress
        chart_ref: bitnami/wordpress
        release_namespace: default
        create_namespace: true
        values_files: 
          - /workspace/wordpress-values.yaml
        wait: true
        timeout: 600s
      environment:
        KUBECONFIG: /workspace/k3s.yaml

    - name: Wait for WordPress deployment
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: default
        label_selectors:
          - app.kubernetes.io/name=wordpress
        wait: yes
        wait_sleep: 10
        wait_timeout: 300
        wait_condition:
          type: Ready
          status: "True"
      environment:
        KUBECONFIG: /workspace/k3s.yaml

    - name: Get WordPress credentials
      shell: |
        echo "WordPress URL: http://{{ hostvars['aws_machine']['ansible_host'] }}:30080"
        echo "WordPress Admin Username: admin"
        echo "WordPress Admin Password: $(kubectl get secret --namespace default wordpress -o jsonpath="{.data.wordpress-password}" | base64 -d)"
        echo "MariaDB Root Password: $(kubectl get secret --namespace default wordpress-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d)"
        echo "MariaDB Password: $(kubectl get secret --namespace default wordpress-mariadb -o jsonpath="{.data.mariadb-password}" | base64 -d)"
      environment:
        KUBECONFIG: /workspace/k3s.yaml
      register: credentials

    - name: Display WordPress credentials
      debug:
        var: credentials.stdout_lines